version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - /home/adsman/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test


  springboot-app:
    depends_on:
      - mysqldb
#    container_name: spring-app
    restart: always
    build: .
#    image: springbooot-app
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306



























#version: "3.5"
#
##volumes:
##  pg_demo:
#services:
##  mysqldb:
##    image: mysql:8.0
###    command: --default-authentication-plugin=mysql_native_password
##    platform: linux/x86_64
##    container_name: mysqldb8
##    restart: always
##    environment:
##      - MYSQL_USER=user
##      - MYSQL_DB=dba
##      - MYSQL_PASSWORD=password
##      - MYSQL_ROOT_PASSWORD=root
##    ports:
##      - "3006:3006"
##    volumes:
##      - ./init.sql:/var/lib/mysqldb/init.sql
##    healthcheck:
##      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
##      timeout: 20s
##      retries: 10
##    extra_hosts:
##      - "add-host host.docker.internal:host-gateway"
##    networks: user-mysql
#
#
#
#
#  app:
##    depends_on:
##      - "mysqldb"
##    links:
##      - mysqldb
#    container_name: app
#
#    image: app
#    restart: always
#    build:
#      dockerfile: Dockerfile
#      context: "./"
#    ports:
#      - "8080:8080"
#
#
##    networks:
##      - net_s
##    environment:
##      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/dba?createDatabaseIfNotExist=true
##      SPRING_DATASOURCE_USERNAME: user
##      SPRING_DATASOURCE_PASSWORD: password
#
#
##networks:
##  net_s:
##    name: custom
##    networks:
##      - spring_net
#
##  postgres_demo:
##    image: postgres:10
##    restart: always
##    environment:
##      - POSTGRES_USER=user
##      - POSTGRES_DB=dba
##      - POSTGRES_PASSWORD=pass
##    volumes:
##      - "pg_demo:/var/lib/postgresql/data"
##    ports:
##      - "5432:5432"
#
#
#
##    environment:
##      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres_demo:5432/dba"
##      JAVA_OPTS: '-Xmx512m'
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
##version: "3"
##services:
##  mysqldb:
##    platform: linux/x86_64
##    container_name: mysqldb
##    image: mysql:8.0
###    command: --default-authentication-plugin=caching_sh2_password
##    restart: always
###    volumes:
###      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
##    environment:
##      MYSQL_DATABASE: dba
##      MYSQL_USER: ads
##      MYSQL_PASSWORD: 123456
##      MYSQL_ROOT_PASSWORD: 123456
##    ports:
##      - "3307:3306"
###  spring-app:
###    image: demo
###    restart: always
###    ports:
###      - "8080:8080"
###    environment:
###      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-mysqldb:3306/dba?autoReconnect=true&useSSL=false
###      SPRING_DATASOURCE_USERNAME: "root"
###      SPRING_DATASOURCE_PASSWORD: "root"
###    build:
###      dockerfile: Dockerfile
###      context: "./"
###
###    depends_on:
###      - "mysql-mysqldb"
##
##
##version: "3"
##services:
##  mysql:
##    build: docker/mysql
##    container_name: mysql8
##    ports:
##      - "3306:3306"